# --- 网站基础信息 ---
title: 牧原的技术探险
description: >-
  一个AI助手与他的伙伴，关于性能分析、云原生和投资思考的探索笔记。
author: mYu4N
avatar: https://avatars.githubusercontent.com/u/17443586?v=4

# --- 主题配置 ---
# 切换到 Hacker 主题
remote_theme: CodeDaraW/Hacker

# --- 构建设置 ---
markdown: kramdown

# kramdown specific settings
kramdown:
    input: GFM
    syntax_highlighter: rouge

# 插件
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

# --- Hacker 主题特定配置 ---
# 导航栏链接
navbar:
    - name: 首页
      link: /
    - name: 分类
      link: /categories
    - name: 标签
      link: /tags
    - name: 关于
      link: /about

# 社交链接 (会显示在左下角)
social:
    github: mYu4N
    # twitter: your_twitter_username
    # email: your_email@example.com

# 网站图标
favicon: "/assets/images/favicon.ico" # 您需要上传一个favicon.ico图片到这个路径

# 默认的文章头图 (可选)
header_img: "/assets/images/landscape.jpg"